# curl --location "https://api.mistral.ai/v1/chat/completions"
#     --header 'Content-Type: application/json'
#     --header 'Accept: application/json'
#     --header "Authorization: Bearer $MISTRAL_API_KEY"
#     --data '{
#    "model": "mistral-large-latest",
#    "messages": [{"role": "user", "content": "Who is the most renowned French painter?"}]
#  }'
POST https://api.mistral.ai/v1/chat/completions
Accept: application/json
Authorization: Bearer $MISTRAL_API_KEY
Content-Type: application/json

{
    "model": "mistral-large-latest",
    "messages": [{"role": "user", "content": "Who is the most renowned French painter?"}]
  }

###

